<html>
  <head>
    <title>Music Collection Management</title>
    <style>
      body {
        font-family: Verdana, sans-serif;
        font-size: 10pt;
      }
      table {
        font-size: 80%;
        border-collapse: collapse;
        border-spacing: 0;
        border: 1px solid #000000;
        /* center the table */
        margin-left: auto;
        margin-right: auto;
      }
      th {
        border: 1px solid #000000;
      }
      td, th {
        text-align: center;
        padding: 1em;
      }
      .highlight {
        background-color: #99CCFF;
      }
      .flag {
        color: #FF0000;
        /*font-weight: bold;*/
      }
    </style>
  </head>
  <body>
    <h1>Music Collection Management</h1>
    <hr>
